storage: upgrade MinIO to its latest version
readthedocs/common pull request #90
Opened 2021-07-12 09:27 UTC by humitos

Following #89 to upgrade MinIO to its latest version.

2021-07-12 14:17 UTC, stsewd approved these changes

2021-07-12 16:13 UTC, astrojuanlu requested changes
Can we have docs? 🙃 I can write them myself by pushing to this branch before merging. As far as I understand there's no rush to upgrade MinIO?

2021-07-13 10:08 UTC, humitos commented
@astrojuanlu we can! I didn't request a review on this one and marked it as blocked because the MinIO UI has changed considerably and I didn't want to jump into it to learn how to do what we are doing in the new UI.

Note the documentation we have to update is on `readthedocs.org` repository at https://docs.readthedocs.io/en/latest/development/install.html

As you already guessed, there is no rush on merging this PR. I just wanted to open it with the new configs because I've already have read about them.

2021-07-13 10:09 UTC, humitos commented
One extra note: we may need to read if there is any step required to "migrate the data". I don't know if the data structure has changed in this new release, but is worth taking a look at that as well.

2021-07-13 10:12 UTC, astrojuanlu commented
> One extra note: we may need to read if there is any step required to "migrate the data".

How relevant is this for development installations? I mean: sure, it's a pain in the neck having to recreate some projects. I'm just weighing how much effort do we want to put in documenting that.

2021-07-13 10:21 UTC, humitos commented
Yeah, I'm fine dropping the storage and re-creating it honestly. I don't think we need to document it for users and make it public in our docs; I was thinking just about _knowing_ if it's required and if there is something like "execute _this_ command once, and it's done" for the core team only. I'm fine having _that_ command in the description of the PR only.

2022-03-03 16:34 UTC, humitos commented
I just checked this locally and there is no need to migrate data.

2022-03-03 16:36 UTC, merged